comment:
e # show coverage only for the diff

flags:
  backend:
    paths:
      - pontoon/**.py
    carryforward: true

  frontend:
    paths:
      - translate/
    carryforward: true

  non-frontend-js:
    paths:
      - pontoon/static/js/
    carryforward: true
